{% set name = "pyexr" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyexr-{{ version }}.tar.gz
  sha256: c8e222439af5622c24f322fea548e051654796e152dcc9666ccbd1627822d126

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - poetry-dynamic-versioning
    - python {{ python_min }}
  run:
    - numpy
    - openexr-python
    - python >={{ python_min }}

test:
  imports:
    - pyexr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tvogels/pyexr
  summary: A simple EXR IO-library for Python that simplifies the use of OpenEXR
  dev_url: https://github.com/tvogels/pyexr
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jeongseok-meta
